layout_spectrum: 0.9187113867808908
typography_spectrum: 0.6136702081976034
color:
  brandStrength: 0.5340873930844857
  lightness: 0.41525373280380323
  saturation: 0.2623871741354429
  rhythmicContrast: 0.16422803152324908
  brandColors:
    - '#6EDBD8'
    - '#2294A4'
    - '#8FF5CE'
    - '#3AABB4'
    - '#54C3C6'
content_rating:
  adult: false
github: true
opengraph:
  type: ''
analytics:
  facebook: '256996934723442'
  google: UA-90994675-1
author:
  name: Roberto Esquenazi
  email: robertoesquenazi@gmail.com
logo: null
name: NIU PANAMA
url: 'http://niupanama.com/'
navigation:
  - name: About Us
    id: e49b3fe3-4d03-405c-bc44-1a5c94559923
    type: content
  - name: The Board
    id: d3b2d4aa-a6a0-49b0-a16b-82d6474daf2d
    type: content
  - name: Contact Us
    id: 7d44aeed-b0be-4e36-aaf4-654d1944babb
    type: content
title: NIU PANAMA
content: []
description: REDEFINING THEATRE
favicon: null
