typography_spectrum: 0.14326553236988218
content_rating:
  adult: false
color:
  brandStrength: 0.6651273037126233
  lightness: 0.062070949465903164
  saturation: 0.020417772290933105
  rhythmicContrast: 0.6901977547786502
  brandColors:
    - '#6EDBD8'
    - '#2294A4'
    - '#8FF5CE'
    - '#3AABB4'
    - '#54C3C6'
github: true
opengraph:
  type: ''
layout_spectrum: 0.901506259581904
analytics:
  facebook: '256996934723442'
  google: UA-90994675-1
author:
  name: Roberto Esquenazi
  email: robertoesquenazi@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/189b9fce-de58-4a9e-95e3-c127500bfec3.png
name: NIU PRODUCTIONS
url: 'http://niupanama.com/'
navigation:
  - name: About Us
    id: e49b3fe3-4d03-405c-bc44-1a5c94559923
    type: content
  - name: The Board
    id: d3b2d4aa-a6a0-49b0-a16b-82d6474daf2d
    type: content
  - name: Contact Us
    id: ad24b86e-ed64-4120-b331-c7615aee029d
    type: content
  - name: Upcoming Productions
    url: 'http://www.facebook.com/pg/niuproductions/events/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8f126bcb-23e9-4739-a194-1f410047e823.png
title: NIU PRODUCTIONS
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/1f5f23eb-53fe-48f9-a59d-8d0aaea65187.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/1f5f23eb-53fe-48f9-a59d-8d0aaea65187.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/5e8a0144-46b3-4f83-9e05-88a6e84e98d2.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/5e8a0144-46b3-4f83-9e05-88a6e84e98d2.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
coverPrefs:
  filter: false
description: What's NIU? ™
purpose:
  - type: external
    url: 'https://www.facebook.com/niuproductions/'
    label: Facebook
  - type: contact
    url: 'tel:61308800'
    label: Call Now
